'\" t
.\"     Title: SMIME-SMTP-FILTER
.\"    Author: Joachim Breitner <joachim.breitner@itomig.de>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 01/15/2010
.\"    Manual: User Manuals
.\"    Source: smime-smtp-filter
.\"  Language: English
.\"
.TH "SMIME\-SMTP\-FILTER" "1" "01/15/2010" "smime-smtp-filter" "User Manuals"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
smime-smtp-filter \- digitally signs outgoing e\-mail messages
.SH "SYNOPSIS"
.HP \w'\fBsmime\-smtp\-filter\fR\ 'u
\fBsmime\-smtp\-filter\fR {\fB\-k\ \fR\fB\fIfile\&.pem\fR\fR | \fB\-\-keyfile\ \fR\fB\fIfile\&.pem\fR\fR}
.HP \w'\fBsmime\-smtp\-filter\fR\ 'u
\fBsmime\-smtp\-filter\fR {\fB\-h\fR | \fB\-\-help\fR}
.SH "DESCRIPTION"
.PP
\fBsmime\-smtp\-filter\fR
reads an e\-mail message from the standard input, signs it using the given S/MIME key, and passes it to standard output\&. It is meant to be useed as a filter for
\fBproxsmtp\fR(8)\&.
.SH "OPTIONS"
.PP
\fB\-k \fR\fB\fIfile\&.pem\fR\fR, \fB\-\-keyfile \fR\fB\fIfile\&.pem\fR\fR
.RS 4
Required\&. PEM certificate to use to sign the e\-mail messages\&.
.RE
.SH "SEE ALSO"
.PP
\fBproxsmtp\fR(8)
.SH "AUTHOR"
.PP
\fBJoachim Breitner\fR <\&joachim\&.breitner@itomig\&.de\&>
.RS 4
Original author of smime\-smtp\-proxy\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2008-2009 Joachim Breitner
.br
